export const FETCH_ROUTE_LIST = "FETCH_ROUTE_LIST";
export const UPDATE_CURRENT_ROUTES = "UPDATE_CURRENT_ROUTES";
export const UPDATE_CURRENT_ROUTE = "UPDATE_CURRENT_ROUTE";
export const UPDATE_CACHE_ROUTES = "UPDATE_CACHE_ROUTES";
export const UPDATE_DETAILS = "UPDATE_DETAILS";